# Generated by Django 5.1.1 on 2024-09-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollNo',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
