# Generated by Django 5.1 on 2024-09-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_app_model_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_model',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
