# Generated by Django 5.1 on 2024-08-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_table',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='home_table',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
